languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
- "app/assets/javascripts/wysihtml.js"
- "app/assets/javascripts/wysihtml5-0.4.0pre.js"
- "app/assets/javascripts/bootstrap-editable.js"
- "app/assets/javascripts/soundmanager2.js"
- "lib/rights_scrapers/features/support/collect_ascap_member_works.rb"
- "app/assets/javascripts/wysihtml5-0.4.0pre.js"
- "app/assets/javascripts/bootstrap/bootstrap.js"
- "app/assets/javascripts/apulum/validate.js"
- "app/assets/javascripts/jquery.fancybox.js"
- "doc/api/js/searchdoc.js"
- "app/assets/javascripts/jquery.blockUI.js"
- "doc/api/js/searcher.js"
- "doc/api/js/navigation.js"
- "app/assets/javascripts/jquery.slimscroll.js"