development:
  s3_key_id: 'AKIAJ47WVOTGNOOO56WQ'
  s3_access_key: 'JgwhuiWOOFEh5HwnFdDrriNKNWcZSNdG+LDZZQzX'
  aws_s3_bucket: 'digiramp-widget'

production:
  s3_key_id: 'AKIAJ47WVOTGNOOO56WQ'
  s3_access_key: 'JgwhuiWOOFEh5HwnFdDrriNKNWcZSNdG+LDZZQzX'
  aws_s3_bucket: 'digiramp-widget'
  
  
  
  

  