#development:
#  s3_key_id: 'AKIAJOHXU7T6MPWRNU3A'
#  s3_access_key: 'b3EQsgRL1suxxu5JuD7Kn7ug8W4jn68Rkj1fGodP'
#  aws_s3_bucket: 'digiramp'
#  
#production:
#  s3_key_id: 'AKIAJOHXU7T6MPWRNU3A'
#  s3_access_key: 'b3EQsgRL1suxxu5JuD7Kn7ug8W4jn68Rkj1fGodP'
#  aws_s3_bucket: 'digiramp'
  

#development:
#  s3_key_id: 'AKIAJ47WVOTGNOOO56WQ'
#  s3_access_key: 'JgwhuiWOOFEh5HwnFdDrriNKNWcZSNdG+LDZZQzX'
#  aws_s3_bucket: 'digiramp-widget'
  
#production:
#  s3_key_id: 'AKIAJ47WVOTGNOOO56WQ'
#  s3_access_key: 'JgwhuiWOOFEh5HwnFdDrriNKNWcZSNdG+LDZZQzX'
#  aws_s3_bucket: 'digiramp-widget'
  
  
  
  

  