development:
  s3_key_id: 'AKIAIYHFZPYR6SXTZTAA'
  s3_access_key: 'EZEQeukdjsPnLRMdoVEp0IBTSVShog8XUh93EJT+'
  aws_s3_bucket: 'digiramp-widget'

production:
  s3_key_id: 'AKIAIYHFZPYR6SXTZTAA'
  s3_access_key: 'EZEQeukdjsPnLRMdoVEp0IBTSVShog8XUh93EJT+'
  aws_s3_bucket: 'digiramp-widget'
  
  
  
  

  