#development:
#  s3_key_id: 'AKIAIYHFZPYR6SXTZTAA'
#  s3_access_key: 'EZEQeukdjsPnLRMdoVEp0IBTSVShog8XUh93EJT+'
#  aws_s3_bucket: 'digiramp'
#  
#production:
#  s3_key_id: 'AKIAIYHFZPYR6SXTZTAA'
#  s3_access_key: 'EZEQeukdjsPnLRMdoVEp0IBTSVShog8XUh93EJT+'
#  aws_s3_bucket: 'digiramp'
  

#development:
#  s3_key_id: 'AKIAJ47WVOTGNOOO56WQ'
#  s3_access_key: 'JgwhuiWOOFEh5HwnFdDrriNKNWcZSNdG+LDZZQzX'
#  aws_s3_bucket: 'digiramp-widget'
  
#production:
#  s3_key_id: 'AKIAJ47WVOTGNOOO56WQ'
#  s3_access_key: 'JgwhuiWOOFEh5HwnFdDrriNKNWcZSNdG+LDZZQzX'
#  aws_s3_bucket: 'digiramp-widget'
  
  
  
  

  