development:
  ws_access_key_id: AKIAJN4UDAY5IF3CRYDA
  aws_secret_access_key: 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


test: &test
  ws_access_key_id: AKIAJN4UDAY5IF3CRYDA
  aws_secret_access_key: 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

production:
  ws_access_key_id: AKIAJN4UDAY5IF3CRYDA
  aws_secret_access_key: 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
