development:
  paypal_host: https://www.sandbox.paypal.com
  #app_host: http://3cGSs4+FIZYz3YOuxw8l.ngrok.com
  app_host: http://2542d042.ngrok.com/
test:
  

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  paypal_host: https://www.paypal.com
  app_host: http://2542d042.ngrok.com/