development:
  # the jquery_sdk version you want to use, read up on it here:
  # https://transloadit.com/blog/2013/02/transloadit-javascript-plugin-and-jquery-1-9
  # defaults to latest
  # use "v1.0.0" if you need IE6 support (using jQuery < 1.9)
  jquery_sdk_version: 'latest'
  auth:
    key     : '0741ea509a4811e387a405b50320e241'
    secret  : '2711f7dcc36149362c04cf70ff6c4a0f88c4b942' # this is optional, but highly recommended, https://transloadit.com/docs/authentication
    duration: 1800 # 30 minute validity period for signed upload forms

  templates:
    # template identified by template_id
    waveform_to_s3: '03eaa4d09a4f11e3a2cee7a07df3ee1a'
    recording_with_thumbs: '0a85f360d48011e38bdd950983062869'
    digiramp_video: '1d318760cd8011e3adcb670cdc24d59b'
    image_files_to_s3: 'd8c43c80d0a411e3a1f42dc1b62a296b'

    
production:
  # the jquery_sdk version you want to use, read up on it here:
  # https://transloadit.com/blog/2013/02/transloadit-javascript-plugin-and-jquery-1-9
  # defaults to latest
  # use "v1.0.0" if you need IE6 support (using jQuery < 1.9)
  jquery_sdk_version: 'latest'
  auth:
    key     : '0741ea509a4811e387a405b50320e241'
    secret  : '2711f7dcc36149362c04cf70ff6c4a0f88c4b942' # this is optional, but highly recommended, https://transloadit.com/docs/authentication
    duration: 1800 # 30 minute validity period for signed upload forms

  templates:
    # template identified by template_id
    waveform_to_s3: '03eaa4d09a4f11e3a2cee7a07df3ee1a'
    recording_with_thumbs: '0a85f360d48011e38bdd950983062869'
    digiramp_video: '1d318760cd8011e3adcb670cdc24d59b'
    image_files_to_s3: 'd8c43c80d0a411e3a1f42dc1b62a296b'
  #templates:
  #  # template identified by template_id
  #  #s3_store: 'S3_STORE_TEMPLATE_ID'
  #
  #  # template defined inline
  #  image_resize:
  #    steps:
  #      resize:
  #        robot : '/image/resize'
  #        width : 320
  #        height: 200
