development:
  # the jquery_sdk version you want to use, read up on it here:
  # https://transloadit.com/blog/2013/02/transloadit-javascript-plugin-and-jquery-1-9
  # defaults to latest
  # use "v1.0.0" if you need IE6 support (using jQuery < 1.9)
  jquery_sdk_version: 'latest'
  auth:
    key     : '0741ea509a4811e387a405b50320e241'
    secret  : '2711f7dcc36149362c04cf70ff6c4a0f88c4b942' # this is optional, but highly recommended, https://transloadit.com/docs/authentication
    duration: 1800 # 30 minute validity period for signed upload forms

  templates:
    # template identified by template_id
    waveform_to_s3: '03eaa4d09a4f11e3a2cee7a07df3ee1a'
    recording_with_thumbs: '6f8e3bb0abcb11e38c97dbdec2e95869'
    digiramp_video: '1d318760cd8011e3adcb670cdc24d59b'

    # template defined inline
    #image_resize:
    #  steps:
    #    resize:
    #      robot : '/image/resize'
    #      width : 320
    #      height: 200
    #      
    ## template defined inline
    #audio_convert:
    #  steps:
    #    resize:
    #      robot : '/audio/waveform'
    #      width : 320
    #      height: 200
    #      
    #    stored_segments: {
    #          robot: "/s3/store",
    #          use: "resize",
    #
    #          bucket: "digiramp",
    #          key: "AKIAIVATNWTNMQZKK2VA",
    #          secret: "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"
    #        }
    #
production:
  # the jquery_sdk version you want to use, read up on it here:
  # https://transloadit.com/blog/2013/02/transloadit-javascript-plugin-and-jquery-1-9
  # defaults to latest
  # use "v1.0.0" if you need IE6 support (using jQuery < 1.9)
  jquery_sdk_version: 'latest'
  auth:
    key     : '0741ea509a4811e387a405b50320e241'
    secret  : '2711f7dcc36149362c04cf70ff6c4a0f88c4b942' # this is optional, but highly recommended, https://transloadit.com/docs/authentication
    duration: 1800 # 30 minute validity period for signed upload forms

  templates:
    # template identified by template_id
    waveform_to_s3: '03eaa4d09a4f11e3a2cee7a07df3ee1a'
    recording_with_thumbs: '6f8e3bb0abcb11e38c97dbdec2e95869'
    digiramp_video: '1d318760cd8011e3adcb670cdc24d59b'
  #templates:
  #  # template identified by template_id
  #  #s3_store: 'S3_STORE_TEMPLATE_ID'
  #
  #  # template defined inline
  #  image_resize:
  #    steps:
  #      resize:
  #        robot : '/image/resize'
  #        width : 320
  #        height: 200
