development:
  adapter: active_record
  active_record_adapter: postgresql
  database: digiramp_development
test:
  collecting: false
production:
  adapter: active_record
  active_record_adapter: postgresql
  database: digiramp_production